- name: ping dynamic inventory
  hosts: build

- name: Install build-packages
  hosts: build
  become: yes

  tasks:
  - name: apt update
    apt:
      update-cahe: yes



  - name: Install packeges
    apt:
      name:
      - docker.io
      - git
      - docker-compose
      state: present





- name: Install stage-packages
  hosts: stage
  become: yes

  tasks:

  - name: apt update
    apt:
      update-cahe: yes

  - name: Install packeges
    apt:
      name:
      - docker.io
      - git
      state: present

